### ISSUE TITLE
Add an example of how to use your scripts

### ISSUE THREAD

**Issue by ever3001** [Aderr0/aws-shadows-http-api#1]
Please add an example in the README on how to use the application. I am having trouble understanding how to create the configuration file and utilize the script.sh. It would be helpful to have a guide like this:

**Step 1**: Create the configuration file by using the template.conf as a template and add the necessary variables:

```shell
cp template.conf my_conf.conf
```

In the new file "my_conf.conf" add the following variables

THING_NAME: This is the name of the device, this variable should be a string, for example: "my-device"
AWS_ACCESS_KEY_ID: This is...

**Step 2**: Call the script.sh using the previously created configuration file and specifying the type of method you want to use. For example, to get a shadow:

```shell
./script.sh my_conf.conf GET
```

If the script is working properly, you should receive a message in the terminal:

```shell
Shadow {
  ...
}
```

Please also make sure the variables for config file is complete before you run the script.

**Comment by Aderr0** [comment]
First of all, thank you for your review. 

You are totally write and I will add this section in the README. 

About your second point, in the python app, i'm using a command line argument parser that check if required arguments are passed. So, as the parameters in the configuration file are defined as required, the app stop if one is missing. Isn't it enough ? Or have you ran into an issue ?

**Comment by Aderr0** [comment]
Done

**Comment by Aderr0** [comment]
There is a new section in README and it will be update with new features coming up
